### ISSUE TITLE
Suggestion: Add additional buffs

### ISSUE THREAD

**Issue by jmusick** [WittBulter/Nioro#5]
This addon looks great but would love to see the ability to have 6 buffs visible instead of the default 3.

**Comment by WittBulter** [comment]
thanks for your contribution, this is a good suggestion, but modifying `max_buff` requires testing more, i will append this func in the next future version, but I can't guarantee the release time.
please pay attention to my curseforge update.

**Comment by WittBulter** [comment]
progress: #9
